production: true

http:
  host: http://hornbill.nikhilcodes.in
  port: 80

db:
  postgres:
    db_name: hornbilldb
    password: 123456
    user: alpha-n1khil
    port: 5432
    host: db

api:
  key: 123abc
